### ISSUE TITLE
missing script?

### ISSUE THREAD

**Issue by tamaraprieto** [anne-marie-lyne/Compare_tree_reconstruction_microsatellites#1]
Hi Anne Marie, 
Thanks for the simulator! It is so convenient. I was trying to understand it in detail when I realized that one script called `gillespieSC.R` may be missing. Within the first lines of the script called `run_repeats_inference_cluster.R`, you wrote that this script (gillespieSC.R) is the generator of the `true_tree_rands_gil_*.RData` file. I have seen that you have another repo with a script called `gillespie_simulate_SC_compartment.R` but as far as I know it is not generating the same objects. 
Thank you!

**Comment by anne-marie-lyne** [comment]
Hi!

Glad to see you are using the simulator!

Yes, I didn’t include that script, instead I put one example output from that script: true_tree_rands_gil_death02.RData <https://github.com/anne-marie-lyne/Compare_tree_reconstruction_microsatellites/blob/master/true_tree_rands_gil_death02.RData>, which is tr=5.

I’ve now added the script to simulate your own trees, hope it’s clear enough how it works.

Thanks,
Anne-Marie

**Comment by tamaraprieto** [comment]
Thank you so much!
